version: '3'

services:
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafna:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    depends_on: ["prom-server"]
